### ISSUE TITLE
as.cgraph breaks if graph has no edges

### ISSUE THREAD

**Issue by ekummerfeld** [tzimiskes/causality#28]
Very rarely, bootstrapping a real data set may result in a data set whose correlations are weak enough that no edges are identified. When this happens, Tetrad outputs a graph object that contains nodes but whose list of edges is empty. When this happens as.cgraph throws an error, exiting whatever loop it's inside of. Ideally, as.cgraph should just convert this to a cgraph with the same nodes but no edges.

**Comment by tzimiskes** [comment]
I think i fixed this, but changes might be on the development branch. Will
look into it

**Comment by tzimiskes** [comment]
Can you send me the error output? Or the empty Tetrad graph (as an RData file)?

**Comment by ekummerfeld** [comment]
I closed all that but it shouldn't be hard to replicate. Will try to do that quick and upload it.

**Comment by ekummerfeld** [comment]
> thisgraph$edges
list()
> capture.output(
+       est_graph <- as.cgraph(thisgraph)
+     )
Error in strsplit(edges[i], " ") : non-character argument


I can't attach a RData to this apparently, will send the saved empty graph object in an email.

**Comment by tzimiskes** [comment]
This should be fixed now
