### ISSUE TITLE
possible dag to pattern bug

### ISSUE THREAD

**Issue by tzimiskes** [tzimiskes/causality#4]
X1 --> X2
X2 --> X3
X3 --- X4

results in

X1 --> X2
X2 --> X3
X3 --> X4

X1 --> X2
X2 --> X3
X4 --- X3

results in

X1 --> X2
X2 --> X3
X4 --> X3

is this good?

solution to is maximally orient pdag? aka meek?
but, #3 is present so this can't be tested

**Comment by ekummerfeld** [comment]
X1 --> X2
X2 --> X3
X4 --- X3

results in

X1 --> X2
X2 --> X3
X4 --> X3


This looks like a bug. should be X3 -> X4. Somehow the fact that X4 appears before X3 in X4 --- X3 has led to the meek rule being applied incorrectly to *produce* a collider rather than *prevent* one.

**Comment by tzimiskes** [comment]
Technically this error is caused by dag to pattern,


Though there was a related meek rules
bug that has been fixed

It is possible that I may need to rewrite some code to deal with these
undirected edges but I do not know until I do further tests (ie meek rules
3/4)

One of my current problems is converting pdags to patterns, which is why
this issue exists as wierdness is happening

**Comment by tzimiskes** [comment]
solution, pick dag first, then pattern
