### ISSUE TITLE
a wierd thing

### ISSUE THREAD

**Issue by tzimiskes** [tzimiskes/causality#7]
according to meek rules, this pdag, A

1 --> 2
2 --> 3
3 --> 4
4 --- 1

should be oriented to the
1 -->  2
2 --> 3
3 --> 4
4 --> 1

which is not a pdag.
 
I'm guessing this has to do with the fact that changing the below DAG to A destroys an unshielded collider,
1 --> 2
2 --> 3
3 --> 4
1 --> 4

My question is: why isn't A a PDAG?

This paper (referenced in Pearl) contains a definition
http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.74.5538&rep=rep1&type=pdf

**Comment by tzimiskes** [comment]
I see.

The equivalence class of this is just an undirected square, yes?

picking a dag out of A, then patterning will result in in either a cyclic graph (un patternable), or 

1 --> 4 
3 --> 4
1 --- 2
2 ---3
 
I'm just not certain how to deal with this (special case).

turning A into a pattern should result in 

1 --- 2
2 --- 3
3 --- 4
4 --- 1

Right? Am I wrong?

**Comment by ekummerfeld** [comment]
The undirected square is (perhaps unexpectedly) also not a pattern. if that is the adjacency structure, the only way to avoid a cycle is to have one or two unshielded colliders. As such the fully undirected square is not a pattern.

Ultimately I don't think there is a need to turn all pdags into patterns. What do you need that functionality for? Some pdags don't have patterns (e.g. your examples). That's Okay.

**Comment by tzimiskes** [comment]
I'm fine with that, but I need way to detect this so I can tell the user
"nope"

I don't know if it's sufficient to meek the graph, then throw an error if
it becomes cyclic.

**Comment by tzimiskes** [comment]
I guess technically the paper I linked has an algorithm to test for this. I
think?

**Comment by ekummerfeld** [comment]
Yeah that paper is proposing an algorithm for exactly that problem, hehe.

Honestly it may be fine to Meek the graph and throw an error if it creates a cycle. In fact, I would be a little surprised if that doesn't work (but not SUPER surprised).

**Comment by tzimiskes** [comment]
Special cases are annoying.

For now I'll probably do the cycle test and make a note of it as a
possible/ known bug

**Comment by ekummerfeld** [comment]
That plan sounds good to me.

**Comment by ekummerfeld** [comment]
If you want to see some fun special cases, wait til I show you how t-separation works, and spider models. conditional independence is child's play by comparison.
